### ISSUE TITLE
Support for koa@2

### ISSUE THREAD

**Issue by bertofer** [koajs/koa-range#10]
As the title says, would be great to have a branch (and npm version published) with support for koa version 2.

I'm preparing a PR

**Comment by bertofer** [comment]
I have added compatibility here https://github.com/bertofer/koa-range

But I wouldn't merge into master, could you create a new branch 'next' or similar where to merge for koa 2 version?

**Comment by coderhaoxin** [comment]
@bertofer you can submit a PR to master, @yorkie could merge it to a new branch (such as `next`)

**Comment by yorkie** [comment]
@coderhaoxin is right, just create a pull-request to master

**Comment by yorkie** [comment]
Fixed at #11
