### ISSUE TITLE
Please release a new version to support koa@1 to fix content-length

### ISSUE THREAD

**Issue by dead-horse** [koajs/koa-range#12]
https://github.com/koajs/koa-range/commit/4b0c0b658467595179522582497060cac20e984e

this commit need release a new version to support koa@1

/cc @yorkie

**Comment by yorkie** [comment]
Hi @dead-horse 4b0c0b658467595179522582497060cac20e984e should be included after v0.3.0, it was bumped at 3d18e9f18e450a48e6464f4497e8b619e7310e14.

**Comment by dead-horse** [comment]
0.2.2
