### ISSUE TITLE
transfer to org

### ISSUE THREAD

**Issue by jonathanong** [koajs/koa-range#6]
transfer to me and i can transfer it in if you can't transfer it in yourself

**Comment by jonathanong** [comment]
and add coderhaoxin and tejasmanohar

**Comment by yorkie** [comment]
Transfer requested to @jonathanong has been sent, and I did add @coderhaoxin in few month ago

**Comment by jonathanong** [comment]
done!@

**Comment by coderhaoxin** [comment]
:clap:

**Comment by yorkie** [comment]
:-)
