### ISSUE TITLE
Giving an error with empty body

### ISSUE THREAD

**Issue by unicornborn** [koajs/koa-range#7]
I'm using `koa-range` with `koa-better-static`, and the user is making a request with

```
if-modified-since:Fri, 01 Apr 2016 18:21:16 GMT
range:bytes=15110-6381395
```

`koa-better-static` returns `304 NOT MODIFIED` with an empty body because the file has not been modified since that date, but now `koa-range` tries to access `this.body.length` which throws an error as its dereferencing undefined

**Comment by yorkie** [comment]
@unicornborn please try to apply https://github.com/koajs/koa-range/pull/8.patch and see if it works on your machine, thank you :-)

**Comment by yorkie** [comment]
Try with 0.2.1 :-)
